import=["~/.config/alacritty/alacritty-theme/themes/cyber_punk_neon.toml"]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[font.italic]
family = "DejaVuSansM Nerd Font Propo"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style= "Book"


[font.offset]
x = 0
y = -2

[shell]
program = "/usr/bin/tmux"
